!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.21.4)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrapmapping_ (nr, nth, nph, yywt, nx, ny, nz, nnuc,&
     & x0, y0, z0, rho, xnu, r3c, r3l, r3r, dx, dy, dz, dphi, rhonew, xn&
     &unew, muc, mul, mur, phic, phil, phir, tol, f2py_yywt_d0, f2py_yyw&
     &t_d1, f2py_rho_d0, f2py_rho_d1, f2py_rho_d2, f2py_xnu_d0, f2py_xnu&
     &_d1, f2py_xnu_d2, f2py_xnu_d3, f2py_r3c_d0, f2py_r3l_d0, f2py_r3r_&
     &d0, f2py_rhonew_d0, f2py_rhonew_d1, f2py_rhonew_d2, f2py_xnunew_d0&
     &, f2py_xnunew_d1, f2py_xnunew_d2, f2py_xnunew_d3, f2py_muc_d0, f2p&
     &y_mul_d0, f2py_mur_d0, f2py_phic_d0, f2py_phil_d0, f2py_phir_d0)
      integer nr
      integer nth
      integer nph
      integer nx
      integer ny
      integer nz
      integer nnuc
      real*8 x0
      real*8 y0
      real*8 z0
      real*8 dx
      real*8 dy
      real*8 dz
      real*8 dphi
      real*8 tol
      integer f2py_yywt_d0
      integer f2py_yywt_d1
      integer f2py_rho_d0
      integer f2py_rho_d1
      integer f2py_rho_d2
      integer f2py_xnu_d0
      integer f2py_xnu_d1
      integer f2py_xnu_d2
      integer f2py_xnu_d3
      integer f2py_r3c_d0
      integer f2py_r3l_d0
      integer f2py_r3r_d0
      integer f2py_rhonew_d0
      integer f2py_rhonew_d1
      integer f2py_rhonew_d2
      integer f2py_xnunew_d0
      integer f2py_xnunew_d1
      integer f2py_xnunew_d2
      integer f2py_xnunew_d3
      integer f2py_muc_d0
      integer f2py_mul_d0
      integer f2py_mur_d0
      integer f2py_phic_d0
      integer f2py_phil_d0
      integer f2py_phir_d0
      real*8 yywt(f2py_yywt_d0,f2py_yywt_d1)
      real*8 rho(f2py_rho_d0,f2py_rho_d1,f2py_rho_d2)
      real*8 xnu(f2py_xnu_d0,f2py_xnu_d1,f2py_xnu_d2,f2py_xnu_d3)
      real*8 r3c(f2py_r3c_d0)
      real*8 r3l(f2py_r3l_d0)
      real*8 r3r(f2py_r3r_d0)
      real*8 rhonew(f2py_rhonew_d0,f2py_rhonew_d1,f2py_rhonew_d2)
      real*8 xnunew(f2py_xnunew_d0,f2py_xnunew_d1,f2py_xnunew_d2,f2py_xn&
     &unew_d3)
      real*8 muc(f2py_muc_d0)
      real*8 mul(f2py_mul_d0)
      real*8 mur(f2py_mur_d0)
      real*8 phic(f2py_phic_d0)
      real*8 phil(f2py_phil_d0)
      real*8 phir(f2py_phir_d0)
      interface
      
            subroutine mapping_(nr,nth,nph,yywt,nx,ny,nz,nnuc,x0,y0,z0,r&
     &ho,xnu,r3c,r3l,r3r,dx,dy,dz,dphi,rhonew,xnunew,muc,mul,mur,phic,ph&
     &il,phir,tol) 
                integer, intent(in) :: nr
                integer, intent(in) :: nth
                integer, intent(in) :: nph
                real*8, dimension(:,:),intent(in) :: yywt
                integer, intent(in) :: nx
                integer, intent(in) :: ny
                integer, intent(in) :: nz
                integer, intent(in) :: nnuc
                real*8, intent(in) :: x0
                real*8, intent(in) :: y0
                real*8, intent(in) :: z0
                real*8, dimension(:,:,:),intent(in) :: rho
                real*8, dimension(:,:,:,:),intent(in) :: xnu
                real*8, dimension(:),intent(in) :: r3c
                real*8, dimension(:),intent(in) :: r3l
                real*8, dimension(:),intent(in) :: r3r
                real*8, intent(in) :: dx
                real*8, intent(in) :: dy
                real*8, intent(in) :: dz
                real*8, intent(in) :: dphi
                real*8, dimension(:,:,:),intent(inout) :: rhonew
                real*8, dimension(:,:,:,:),intent(inout) :: xnunew
                real*8, dimension(:),intent(in) :: muc
                real*8, dimension(:),intent(in) :: mul
                real*8, dimension(:),intent(in) :: mur
                real*8, dimension(:),intent(in) :: phic
                real*8, dimension(:),intent(in) :: phil
                real*8, dimension(:),intent(in) :: phir
                real*8, intent(in) :: tol
            end subroutine mapping_
      end interface
      call mapping_(nr, nth, nph, yywt, nx, ny, nz, nnuc, x0, y0, z0, rh&
     &o, xnu, r3c, r3l, r3r, dx, dy, dz, dphi, rhonew, xnunew, muc, mul,&
     & mur, phic, phil, phir, tol)
      end

