!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.21.4)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrapmappingx (nr, nth, nph, yywt_, nx, ny, nz, nnuc&
     &, x0, y0, z0, rho_, xnu_, r3c_, r3l_, r3r_, dx, dy, dz, dphi, rhon&
     &ew_, xnunew_, muc_, mul_, mur_, phic_, phil_, phir_, f2py_yywt__d0&
     &, f2py_yywt__d1, f2py_rho__d0, f2py_rho__d1, f2py_rho__d2, f2py_xn&
     &u__d0, f2py_xnu__d1, f2py_xnu__d2, f2py_xnu__d3, f2py_r3c__d0, f2p&
     &y_r3l__d0, f2py_r3r__d0, f2py_rhonew__d0, f2py_rhonew__d1, f2py_rh&
     &onew__d2, f2py_xnunew__d0, f2py_xnunew__d1, f2py_xnunew__d2, f2py_&
     &xnunew__d3, f2py_muc__d0, f2py_mul__d0, f2py_mur__d0, f2py_phic__d&
     &0, f2py_phil__d0, f2py_phir__d0)
      integer nr
      integer nth
      integer nph
      integer nx
      integer ny
      integer nz
      integer nnuc
      real*8 x0
      real*8 y0
      real*8 z0
      real*8 dx
      real*8 dy
      real*8 dz
      real*8 dphi
      integer f2py_yywt__d0
      integer f2py_yywt__d1
      integer f2py_rho__d0
      integer f2py_rho__d1
      integer f2py_rho__d2
      integer f2py_xnu__d0
      integer f2py_xnu__d1
      integer f2py_xnu__d2
      integer f2py_xnu__d3
      integer f2py_r3c__d0
      integer f2py_r3l__d0
      integer f2py_r3r__d0
      integer f2py_rhonew__d0
      integer f2py_rhonew__d1
      integer f2py_rhonew__d2
      integer f2py_xnunew__d0
      integer f2py_xnunew__d1
      integer f2py_xnunew__d2
      integer f2py_xnunew__d3
      integer f2py_muc__d0
      integer f2py_mul__d0
      integer f2py_mur__d0
      integer f2py_phic__d0
      integer f2py_phil__d0
      integer f2py_phir__d0
      real*8 yywt_(f2py_yywt__d0,f2py_yywt__d1)
      real*8 rho_(f2py_rho__d0,f2py_rho__d1,f2py_rho__d2)
      real*8 xnu_(f2py_xnu__d0,f2py_xnu__d1,f2py_xnu__d2,f2py_xnu__d3)
      real*8 r3c_(f2py_r3c__d0)
      real*8 r3l_(f2py_r3l__d0)
      real*8 r3r_(f2py_r3r__d0)
      real*8 rhonew_(f2py_rhonew__d0,f2py_rhonew__d1,f2py_rhonew__d2)
      real*8 xnunew_(f2py_xnunew__d0,f2py_xnunew__d1,f2py_xnunew__d2,f2p&
     &y_xnunew__d3)
      real*8 muc_(f2py_muc__d0)
      real*8 mul_(f2py_mul__d0)
      real*8 mur_(f2py_mur__d0)
      real*8 phic_(f2py_phic__d0)
      real*8 phil_(f2py_phil__d0)
      real*8 phir_(f2py_phir__d0)
      interface
      
            subroutine mappingx(nr,nth,nph,yywt_,nx,ny,nz,nnuc,x0,y0,z0,&
     &rho_,xnu_,r3c_,r3l_,r3r_,dx,dy,dz,dphi,rhonew_,xnunew_,muc_,mul_,m&
     &ur_,phic_,phil_,phir_) 
                integer, intent(in) :: nr
                integer, intent(in) :: nth
                integer, intent(in) :: nph
                real*8, dimension(:,:),intent(in) :: yywt_
                integer, intent(in) :: nx
                integer, intent(in) :: ny
                integer, intent(in) :: nz
                integer, intent(in) :: nnuc
                real*8, intent(in) :: x0
                real*8, intent(in) :: y0
                real*8, intent(in) :: z0
                real*8, dimension(:,:,:),intent(in) :: rho_
                real*8, dimension(:,:,:,:),intent(in) :: xnu_
                real*8, dimension(:),intent(in) :: r3c_
                real*8, dimension(:),intent(in) :: r3l_
                real*8, dimension(:),intent(in) :: r3r_
                real*8, intent(in) :: dx
                real*8, intent(in) :: dy
                real*8, intent(in) :: dz
                real*8, intent(in) :: dphi
                real*8, dimension(:,:,:),intent(inout) :: rhonew_
                real*8, dimension(:,:,:,:),intent(inout) :: xnunew_
                real*8, dimension(:),intent(in) :: muc_
                real*8, dimension(:),intent(in) :: mul_
                real*8, dimension(:),intent(in) :: mur_
                real*8, dimension(:),intent(in) :: phic_
                real*8, dimension(:),intent(in) :: phil_
                real*8, dimension(:),intent(in) :: phir_
            end subroutine mappingx
      end interface
      call mappingx(nr, nth, nph, yywt_, nx, ny, nz, nnuc, x0, y0, z0, r&
     &ho_, xnu_, r3c_, r3l_, r3r_, dx, dy, dz, dphi, rhonew_, xnunew_, m&
     &uc_, mul_, mur_, phic_, phil_, phir_)
      end

