/* File: _interfacemodule.c
 * This file is auto-generated with f2py (version:1.21.4).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri Nov 19 01:11:57 2021
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_interface_error;
static PyObject *_interface_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj, 0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _interface_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _interface_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_WRAPPEDFUNC(mappingx,MAPPINGX)(int*,int*,int*,double*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** mappingx **********************************/
static char doc_f2py_rout__interface_mappingx[] = "\
mappingx(nr,nth,nph,yywt_,nx,ny,nz,nnuc,x0,y0,z0,rho_,xnu_,r3c_,r3l_,r3r_,dx,dy,dz,dphi,rhonew_,xnunew_,muc_,mul_,mur_,phic_,phil_,phir_)\n\nWrapper for ``mappingx``.\
\n\nParameters\n----------\n"
"nr : input int\n"
"nth : input int\n"
"nph : input int\n"
"yywt_ : input rank-2 array('d') with bounds (f2py_yywt__d0,f2py_yywt__d1)\n"
"nx : input int\n"
"ny : input int\n"
"nz : input int\n"
"nnuc : input int\n"
"x0 : input float\n"
"y0 : input float\n"
"z0 : input float\n"
"rho_ : input rank-3 array('d') with bounds (f2py_rho__d0,f2py_rho__d1,f2py_rho__d2)\n"
"xnu_ : input rank-4 array('d') with bounds (f2py_xnu__d0,f2py_xnu__d1,f2py_xnu__d2,f2py_xnu__d3)\n"
"r3c_ : input rank-1 array('d') with bounds (f2py_r3c__d0)\n"
"r3l_ : input rank-1 array('d') with bounds (f2py_r3l__d0)\n"
"r3r_ : input rank-1 array('d') with bounds (f2py_r3r__d0)\n"
"dx : input float\n"
"dy : input float\n"
"dz : input float\n"
"dphi : input float\n"
"rhonew_ : in/output rank-3 array('d') with bounds (f2py_rhonew__d0,f2py_rhonew__d1,f2py_rhonew__d2)\n"
"xnunew_ : in/output rank-4 array('d') with bounds (f2py_xnunew__d0,f2py_xnunew__d1,f2py_xnunew__d2,f2py_xnunew__d3)\n"
"muc_ : input rank-1 array('d') with bounds (f2py_muc__d0)\n"
"mul_ : input rank-1 array('d') with bounds (f2py_mul__d0)\n"
"mur_ : input rank-1 array('d') with bounds (f2py_mur__d0)\n"
"phic_ : input rank-1 array('d') with bounds (f2py_phic__d0)\n"
"phil_ : input rank-1 array('d') with bounds (f2py_phil__d0)\n"
"phir_ : input rank-1 array('d') with bounds (f2py_phir__d0)";
/* extern void F_WRAPPEDFUNC(mappingx,MAPPINGX)(int*,int*,int*,double*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout__interface_mappingx(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  int nr = 0;
  PyObject *nr_capi = Py_None;
  int nth = 0;
  PyObject *nth_capi = Py_None;
  int nph = 0;
  PyObject *nph_capi = Py_None;
  double *yywt_ = NULL;
  npy_intp yywt__Dims[2] = {-1, -1};
  const int yywt__Rank = 2;
  PyArrayObject *capi_yywt__tmp = NULL;
  int capi_yywt__intent = 0;
  PyObject *yywt__capi = Py_None;
  int nx = 0;
  PyObject *nx_capi = Py_None;
  int ny = 0;
  PyObject *ny_capi = Py_None;
  int nz = 0;
  PyObject *nz_capi = Py_None;
  int nnuc = 0;
  PyObject *nnuc_capi = Py_None;
  double x0 = 0;
  PyObject *x0_capi = Py_None;
  double y0 = 0;
  PyObject *y0_capi = Py_None;
  double z0 = 0;
  PyObject *z0_capi = Py_None;
  double *rho_ = NULL;
  npy_intp rho__Dims[3] = {-1, -1, -1};
  const int rho__Rank = 3;
  PyArrayObject *capi_rho__tmp = NULL;
  int capi_rho__intent = 0;
  PyObject *rho__capi = Py_None;
  double *xnu_ = NULL;
  npy_intp xnu__Dims[4] = {-1, -1, -1, -1};
  const int xnu__Rank = 4;
  PyArrayObject *capi_xnu__tmp = NULL;
  int capi_xnu__intent = 0;
  PyObject *xnu__capi = Py_None;
  double *r3c_ = NULL;
  npy_intp r3c__Dims[1] = {-1};
  const int r3c__Rank = 1;
  PyArrayObject *capi_r3c__tmp = NULL;
  int capi_r3c__intent = 0;
  PyObject *r3c__capi = Py_None;
  double *r3l_ = NULL;
  npy_intp r3l__Dims[1] = {-1};
  const int r3l__Rank = 1;
  PyArrayObject *capi_r3l__tmp = NULL;
  int capi_r3l__intent = 0;
  PyObject *r3l__capi = Py_None;
  double *r3r_ = NULL;
  npy_intp r3r__Dims[1] = {-1};
  const int r3r__Rank = 1;
  PyArrayObject *capi_r3r__tmp = NULL;
  int capi_r3r__intent = 0;
  PyObject *r3r__capi = Py_None;
  double dx = 0;
  PyObject *dx_capi = Py_None;
  double dy = 0;
  PyObject *dy_capi = Py_None;
  double dz = 0;
  PyObject *dz_capi = Py_None;
  double dphi = 0;
  PyObject *dphi_capi = Py_None;
  double *rhonew_ = NULL;
  npy_intp rhonew__Dims[3] = {-1, -1, -1};
  const int rhonew__Rank = 3;
  PyArrayObject *capi_rhonew__tmp = NULL;
  int capi_rhonew__intent = 0;
  PyObject *rhonew__capi = Py_None;
  double *xnunew_ = NULL;
  npy_intp xnunew__Dims[4] = {-1, -1, -1, -1};
  const int xnunew__Rank = 4;
  PyArrayObject *capi_xnunew__tmp = NULL;
  int capi_xnunew__intent = 0;
  PyObject *xnunew__capi = Py_None;
  double *muc_ = NULL;
  npy_intp muc__Dims[1] = {-1};
  const int muc__Rank = 1;
  PyArrayObject *capi_muc__tmp = NULL;
  int capi_muc__intent = 0;
  PyObject *muc__capi = Py_None;
  double *mul_ = NULL;
  npy_intp mul__Dims[1] = {-1};
  const int mul__Rank = 1;
  PyArrayObject *capi_mul__tmp = NULL;
  int capi_mul__intent = 0;
  PyObject *mul__capi = Py_None;
  double *mur_ = NULL;
  npy_intp mur__Dims[1] = {-1};
  const int mur__Rank = 1;
  PyArrayObject *capi_mur__tmp = NULL;
  int capi_mur__intent = 0;
  PyObject *mur__capi = Py_None;
  double *phic_ = NULL;
  npy_intp phic__Dims[1] = {-1};
  const int phic__Rank = 1;
  PyArrayObject *capi_phic__tmp = NULL;
  int capi_phic__intent = 0;
  PyObject *phic__capi = Py_None;
  double *phil_ = NULL;
  npy_intp phil__Dims[1] = {-1};
  const int phil__Rank = 1;
  PyArrayObject *capi_phil__tmp = NULL;
  int capi_phil__intent = 0;
  PyObject *phil__capi = Py_None;
  double *phir_ = NULL;
  npy_intp phir__Dims[1] = {-1};
  const int phir__Rank = 1;
  PyArrayObject *capi_phir__tmp = NULL;
  int capi_phir__intent = 0;
  PyObject *phir__capi = Py_None;
  int f2py_yywt__d0 = 0;
  int f2py_yywt__d1 = 0;
  int f2py_rho__d0 = 0;
  int f2py_rho__d1 = 0;
  int f2py_rho__d2 = 0;
  int f2py_xnu__d0 = 0;
  int f2py_xnu__d1 = 0;
  int f2py_xnu__d2 = 0;
  int f2py_xnu__d3 = 0;
  int f2py_r3c__d0 = 0;
  int f2py_r3l__d0 = 0;
  int f2py_r3r__d0 = 0;
  int f2py_rhonew__d0 = 0;
  int f2py_rhonew__d1 = 0;
  int f2py_rhonew__d2 = 0;
  int f2py_xnunew__d0 = 0;
  int f2py_xnunew__d1 = 0;
  int f2py_xnunew__d2 = 0;
  int f2py_xnunew__d3 = 0;
  int f2py_muc__d0 = 0;
  int f2py_mul__d0 = 0;
  int f2py_mur__d0 = 0;
  int f2py_phic__d0 = 0;
  int f2py_phil__d0 = 0;
  int f2py_phir__d0 = 0;
    static char *capi_kwlist[] = {"nr","nth","nph","yywt_","nx","ny","nz","nnuc","x0","y0","z0","rho_","xnu_","r3c_","r3l_","r3r_","dx","dy","dz","dphi","rhonew_","xnunew_","muc_","mul_","mur_","phic_","phil_","phir_",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOOOOOOOOOOOOOO|:_interface.mappingx",\
        capi_kwlist,&nr_capi,&nth_capi,&nph_capi,&yywt__capi,&nx_capi,&ny_capi,&nz_capi,&nnuc_capi,&x0_capi,&y0_capi,&z0_capi,&rho__capi,&xnu__capi,&r3c__capi,&r3l__capi,&r3r__capi,&dx_capi,&dy_capi,&dz_capi,&dphi_capi,&rhonew__capi,&xnunew__capi,&muc__capi,&mul__capi,&mur__capi,&phic__capi,&phil__capi,&phir__capi))
        return NULL;
/*frompyobj*/
  /* Processing variable nr */
    f2py_success = int_from_pyobj(&nr,nr_capi,"_interface.mappingx() 1st argument (nr) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nth */
    f2py_success = int_from_pyobj(&nth,nth_capi,"_interface.mappingx() 2nd argument (nth) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nph */
    f2py_success = int_from_pyobj(&nph,nph_capi,"_interface.mappingx() 3rd argument (nph) can't be converted to int");
  if (f2py_success) {
  /* Processing variable yywt_ */
  ;
  capi_yywt__intent |= F2PY_INTENT_IN;
  capi_yywt__tmp = array_from_pyobj(NPY_DOUBLE,yywt__Dims,yywt__Rank,capi_yywt__intent,yywt__capi);
  if (capi_yywt__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 4th argument `yywt_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    yywt_ = (double *)(PyArray_DATA(capi_yywt__tmp));

  /* Processing variable nx */
    f2py_success = int_from_pyobj(&nx,nx_capi,"_interface.mappingx() 5th argument (nx) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ny */
    f2py_success = int_from_pyobj(&ny,ny_capi,"_interface.mappingx() 6th argument (ny) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nz */
    f2py_success = int_from_pyobj(&nz,nz_capi,"_interface.mappingx() 7th argument (nz) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nnuc */
    f2py_success = int_from_pyobj(&nnuc,nnuc_capi,"_interface.mappingx() 8th argument (nnuc) can't be converted to int");
  if (f2py_success) {
  /* Processing variable x0 */
    f2py_success = double_from_pyobj(&x0,x0_capi,"_interface.mappingx() 9th argument (x0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable y0 */
    f2py_success = double_from_pyobj(&y0,y0_capi,"_interface.mappingx() 10th argument (y0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z0 */
    f2py_success = double_from_pyobj(&z0,z0_capi,"_interface.mappingx() 11st argument (z0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable rho_ */
  ;
  capi_rho__intent |= F2PY_INTENT_IN;
  capi_rho__tmp = array_from_pyobj(NPY_DOUBLE,rho__Dims,rho__Rank,capi_rho__intent,rho__capi);
  if (capi_rho__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 12nd argument `rho_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    rho_ = (double *)(PyArray_DATA(capi_rho__tmp));

  /* Processing variable xnu_ */
  ;
  capi_xnu__intent |= F2PY_INTENT_IN;
  capi_xnu__tmp = array_from_pyobj(NPY_DOUBLE,xnu__Dims,xnu__Rank,capi_xnu__intent,xnu__capi);
  if (capi_xnu__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 13rd argument `xnu_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    xnu_ = (double *)(PyArray_DATA(capi_xnu__tmp));

  /* Processing variable r3c_ */
  ;
  capi_r3c__intent |= F2PY_INTENT_IN;
  capi_r3c__tmp = array_from_pyobj(NPY_DOUBLE,r3c__Dims,r3c__Rank,capi_r3c__intent,r3c__capi);
  if (capi_r3c__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 14th argument `r3c_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    r3c_ = (double *)(PyArray_DATA(capi_r3c__tmp));

  /* Processing variable r3l_ */
  ;
  capi_r3l__intent |= F2PY_INTENT_IN;
  capi_r3l__tmp = array_from_pyobj(NPY_DOUBLE,r3l__Dims,r3l__Rank,capi_r3l__intent,r3l__capi);
  if (capi_r3l__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 15th argument `r3l_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    r3l_ = (double *)(PyArray_DATA(capi_r3l__tmp));

  /* Processing variable r3r_ */
  ;
  capi_r3r__intent |= F2PY_INTENT_IN;
  capi_r3r__tmp = array_from_pyobj(NPY_DOUBLE,r3r__Dims,r3r__Rank,capi_r3r__intent,r3r__capi);
  if (capi_r3r__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 16th argument `r3r_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    r3r_ = (double *)(PyArray_DATA(capi_r3r__tmp));

  /* Processing variable dx */
    f2py_success = double_from_pyobj(&dx,dx_capi,"_interface.mappingx() 17th argument (dx) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dy */
    f2py_success = double_from_pyobj(&dy,dy_capi,"_interface.mappingx() 18th argument (dy) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dz */
    f2py_success = double_from_pyobj(&dz,dz_capi,"_interface.mappingx() 19th argument (dz) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dphi */
    f2py_success = double_from_pyobj(&dphi,dphi_capi,"_interface.mappingx() 20th argument (dphi) can't be converted to double");
  if (f2py_success) {
  /* Processing variable rhonew_ */
  ;
  capi_rhonew__intent |= F2PY_INTENT_INOUT;
  capi_rhonew__tmp = array_from_pyobj(NPY_DOUBLE,rhonew__Dims,rhonew__Rank,capi_rhonew__intent,rhonew__capi);
  if (capi_rhonew__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 21st argument `rhonew_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    rhonew_ = (double *)(PyArray_DATA(capi_rhonew__tmp));

  /* Processing variable xnunew_ */
  ;
  capi_xnunew__intent |= F2PY_INTENT_INOUT;
  capi_xnunew__tmp = array_from_pyobj(NPY_DOUBLE,xnunew__Dims,xnunew__Rank,capi_xnunew__intent,xnunew__capi);
  if (capi_xnunew__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 22nd argument `xnunew_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    xnunew_ = (double *)(PyArray_DATA(capi_xnunew__tmp));

  /* Processing variable muc_ */
  ;
  capi_muc__intent |= F2PY_INTENT_IN;
  capi_muc__tmp = array_from_pyobj(NPY_DOUBLE,muc__Dims,muc__Rank,capi_muc__intent,muc__capi);
  if (capi_muc__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 23rd argument `muc_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    muc_ = (double *)(PyArray_DATA(capi_muc__tmp));

  /* Processing variable mul_ */
  ;
  capi_mul__intent |= F2PY_INTENT_IN;
  capi_mul__tmp = array_from_pyobj(NPY_DOUBLE,mul__Dims,mul__Rank,capi_mul__intent,mul__capi);
  if (capi_mul__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 24th argument `mul_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    mul_ = (double *)(PyArray_DATA(capi_mul__tmp));

  /* Processing variable mur_ */
  ;
  capi_mur__intent |= F2PY_INTENT_IN;
  capi_mur__tmp = array_from_pyobj(NPY_DOUBLE,mur__Dims,mur__Rank,capi_mur__intent,mur__capi);
  if (capi_mur__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 25th argument `mur_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    mur_ = (double *)(PyArray_DATA(capi_mur__tmp));

  /* Processing variable phic_ */
  ;
  capi_phic__intent |= F2PY_INTENT_IN;
  capi_phic__tmp = array_from_pyobj(NPY_DOUBLE,phic__Dims,phic__Rank,capi_phic__intent,phic__capi);
  if (capi_phic__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 26th argument `phic_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    phic_ = (double *)(PyArray_DATA(capi_phic__tmp));

  /* Processing variable phil_ */
  ;
  capi_phil__intent |= F2PY_INTENT_IN;
  capi_phil__tmp = array_from_pyobj(NPY_DOUBLE,phil__Dims,phil__Rank,capi_phil__intent,phil__capi);
  if (capi_phil__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 27th argument `phil_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    phil_ = (double *)(PyArray_DATA(capi_phil__tmp));

  /* Processing variable phir_ */
  ;
  capi_phir__intent |= F2PY_INTENT_IN;
  capi_phir__tmp = array_from_pyobj(NPY_DOUBLE,phir__Dims,phir__Rank,capi_phir__intent,phir__capi);
  if (capi_phir__tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _interface_error,"failed in converting 28th argument `phir_' of _interface.mappingx to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    phir_ = (double *)(PyArray_DATA(capi_phir__tmp));

  /* Processing variable f2py_yywt__d0 */
  f2py_yywt__d0 = shape(yywt_, 0);
  /* Processing variable f2py_yywt__d1 */
  f2py_yywt__d1 = shape(yywt_, 1);
  /* Processing variable f2py_rho__d0 */
  f2py_rho__d0 = shape(rho_, 0);
  /* Processing variable f2py_rho__d1 */
  f2py_rho__d1 = shape(rho_, 1);
  /* Processing variable f2py_rho__d2 */
  f2py_rho__d2 = shape(rho_, 2);
  /* Processing variable f2py_xnu__d0 */
  f2py_xnu__d0 = shape(xnu_, 0);
  /* Processing variable f2py_xnu__d1 */
  f2py_xnu__d1 = shape(xnu_, 1);
  /* Processing variable f2py_xnu__d2 */
  f2py_xnu__d2 = shape(xnu_, 2);
  /* Processing variable f2py_xnu__d3 */
  f2py_xnu__d3 = shape(xnu_, 3);
  /* Processing variable f2py_r3c__d0 */
  f2py_r3c__d0 = shape(r3c_, 0);
  /* Processing variable f2py_r3l__d0 */
  f2py_r3l__d0 = shape(r3l_, 0);
  /* Processing variable f2py_r3r__d0 */
  f2py_r3r__d0 = shape(r3r_, 0);
  /* Processing variable f2py_rhonew__d0 */
  f2py_rhonew__d0 = shape(rhonew_, 0);
  /* Processing variable f2py_rhonew__d1 */
  f2py_rhonew__d1 = shape(rhonew_, 1);
  /* Processing variable f2py_rhonew__d2 */
  f2py_rhonew__d2 = shape(rhonew_, 2);
  /* Processing variable f2py_xnunew__d0 */
  f2py_xnunew__d0 = shape(xnunew_, 0);
  /* Processing variable f2py_xnunew__d1 */
  f2py_xnunew__d1 = shape(xnunew_, 1);
  /* Processing variable f2py_xnunew__d2 */
  f2py_xnunew__d2 = shape(xnunew_, 2);
  /* Processing variable f2py_xnunew__d3 */
  f2py_xnunew__d3 = shape(xnunew_, 3);
  /* Processing variable f2py_muc__d0 */
  f2py_muc__d0 = shape(muc_, 0);
  /* Processing variable f2py_mul__d0 */
  f2py_mul__d0 = shape(mul_, 0);
  /* Processing variable f2py_mur__d0 */
  f2py_mur__d0 = shape(mur_, 0);
  /* Processing variable f2py_phic__d0 */
  f2py_phic__d0 = shape(phic_, 0);
  /* Processing variable f2py_phil__d0 */
  f2py_phil__d0 = shape(phil_, 0);
  /* Processing variable f2py_phir__d0 */
  f2py_phir__d0 = shape(phir_, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&nr,&nth,&nph,yywt_,&nx,&ny,&nz,&nnuc,&x0,&y0,&z0,rho_,xnu_,r3c_,r3l_,r3r_,&dx,&dy,&dz,&dphi,rhonew_,xnunew_,muc_,mul_,mur_,phic_,phil_,phir_,&f2py_yywt__d0,&f2py_yywt__d1,&f2py_rho__d0,&f2py_rho__d1,&f2py_rho__d2,&f2py_xnu__d0,&f2py_xnu__d1,&f2py_xnu__d2,&f2py_xnu__d3,&f2py_r3c__d0,&f2py_r3l__d0,&f2py_r3r__d0,&f2py_rhonew__d0,&f2py_rhonew__d1,&f2py_rhonew__d2,&f2py_xnunew__d0,&f2py_xnunew__d1,&f2py_xnunew__d2,&f2py_xnunew__d3,&f2py_muc__d0,&f2py_mul__d0,&f2py_mur__d0,&f2py_phic__d0,&f2py_phil__d0,&f2py_phir__d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_phir__d0 */
  /* End of cleaning variable f2py_phil__d0 */
  /* End of cleaning variable f2py_phic__d0 */
  /* End of cleaning variable f2py_mur__d0 */
  /* End of cleaning variable f2py_mul__d0 */
  /* End of cleaning variable f2py_muc__d0 */
  /* End of cleaning variable f2py_xnunew__d3 */
  /* End of cleaning variable f2py_xnunew__d2 */
  /* End of cleaning variable f2py_xnunew__d1 */
  /* End of cleaning variable f2py_xnunew__d0 */
  /* End of cleaning variable f2py_rhonew__d2 */
  /* End of cleaning variable f2py_rhonew__d1 */
  /* End of cleaning variable f2py_rhonew__d0 */
  /* End of cleaning variable f2py_r3r__d0 */
  /* End of cleaning variable f2py_r3l__d0 */
  /* End of cleaning variable f2py_r3c__d0 */
  /* End of cleaning variable f2py_xnu__d3 */
  /* End of cleaning variable f2py_xnu__d2 */
  /* End of cleaning variable f2py_xnu__d1 */
  /* End of cleaning variable f2py_xnu__d0 */
  /* End of cleaning variable f2py_rho__d2 */
  /* End of cleaning variable f2py_rho__d1 */
  /* End of cleaning variable f2py_rho__d0 */
  /* End of cleaning variable f2py_yywt__d1 */
  /* End of cleaning variable f2py_yywt__d0 */
  if((PyObject *)capi_phir__tmp!=phir__capi) {
    Py_XDECREF(capi_phir__tmp); }
  }  /*if (capi_phir__tmp == NULL) ... else of phir_*/
  /* End of cleaning variable phir_ */
  if((PyObject *)capi_phil__tmp!=phil__capi) {
    Py_XDECREF(capi_phil__tmp); }
  }  /*if (capi_phil__tmp == NULL) ... else of phil_*/
  /* End of cleaning variable phil_ */
  if((PyObject *)capi_phic__tmp!=phic__capi) {
    Py_XDECREF(capi_phic__tmp); }
  }  /*if (capi_phic__tmp == NULL) ... else of phic_*/
  /* End of cleaning variable phic_ */
  if((PyObject *)capi_mur__tmp!=mur__capi) {
    Py_XDECREF(capi_mur__tmp); }
  }  /*if (capi_mur__tmp == NULL) ... else of mur_*/
  /* End of cleaning variable mur_ */
  if((PyObject *)capi_mul__tmp!=mul__capi) {
    Py_XDECREF(capi_mul__tmp); }
  }  /*if (capi_mul__tmp == NULL) ... else of mul_*/
  /* End of cleaning variable mul_ */
  if((PyObject *)capi_muc__tmp!=muc__capi) {
    Py_XDECREF(capi_muc__tmp); }
  }  /*if (capi_muc__tmp == NULL) ... else of muc_*/
  /* End of cleaning variable muc_ */
  if((PyObject *)capi_xnunew__tmp!=xnunew__capi) {
    Py_XDECREF(capi_xnunew__tmp); }
  }  /*if (capi_xnunew__tmp == NULL) ... else of xnunew_*/
  /* End of cleaning variable xnunew_ */
  if((PyObject *)capi_rhonew__tmp!=rhonew__capi) {
    Py_XDECREF(capi_rhonew__tmp); }
  }  /*if (capi_rhonew__tmp == NULL) ... else of rhonew_*/
  /* End of cleaning variable rhonew_ */
  } /*if (f2py_success) of dphi*/
  /* End of cleaning variable dphi */
  } /*if (f2py_success) of dz*/
  /* End of cleaning variable dz */
  } /*if (f2py_success) of dy*/
  /* End of cleaning variable dy */
  } /*if (f2py_success) of dx*/
  /* End of cleaning variable dx */
  if((PyObject *)capi_r3r__tmp!=r3r__capi) {
    Py_XDECREF(capi_r3r__tmp); }
  }  /*if (capi_r3r__tmp == NULL) ... else of r3r_*/
  /* End of cleaning variable r3r_ */
  if((PyObject *)capi_r3l__tmp!=r3l__capi) {
    Py_XDECREF(capi_r3l__tmp); }
  }  /*if (capi_r3l__tmp == NULL) ... else of r3l_*/
  /* End of cleaning variable r3l_ */
  if((PyObject *)capi_r3c__tmp!=r3c__capi) {
    Py_XDECREF(capi_r3c__tmp); }
  }  /*if (capi_r3c__tmp == NULL) ... else of r3c_*/
  /* End of cleaning variable r3c_ */
  if((PyObject *)capi_xnu__tmp!=xnu__capi) {
    Py_XDECREF(capi_xnu__tmp); }
  }  /*if (capi_xnu__tmp == NULL) ... else of xnu_*/
  /* End of cleaning variable xnu_ */
  if((PyObject *)capi_rho__tmp!=rho__capi) {
    Py_XDECREF(capi_rho__tmp); }
  }  /*if (capi_rho__tmp == NULL) ... else of rho_*/
  /* End of cleaning variable rho_ */
  } /*if (f2py_success) of z0*/
  /* End of cleaning variable z0 */
  } /*if (f2py_success) of y0*/
  /* End of cleaning variable y0 */
  } /*if (f2py_success) of x0*/
  /* End of cleaning variable x0 */
  } /*if (f2py_success) of nnuc*/
  /* End of cleaning variable nnuc */
  } /*if (f2py_success) of nz*/
  /* End of cleaning variable nz */
  } /*if (f2py_success) of ny*/
  /* End of cleaning variable ny */
  } /*if (f2py_success) of nx*/
  /* End of cleaning variable nx */
  if((PyObject *)capi_yywt__tmp!=yywt__capi) {
    Py_XDECREF(capi_yywt__tmp); }
  }  /*if (capi_yywt__tmp == NULL) ... else of yywt_*/
  /* End of cleaning variable yywt_ */
  } /*if (f2py_success) of nph*/
  /* End of cleaning variable nph */
  } /*if (f2py_success) of nth*/
  /* End of cleaning variable nth */
  } /*if (f2py_success) of nr*/
  /* End of cleaning variable nr */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of mappingx ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"mappingx",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(mappingx,MAPPINGX),(f2py_init_func)f2py_rout__interface_mappingx,doc_f2py_rout__interface_mappingx},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_interface",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};

PyMODINIT_FUNC PyInit__interface(void) {
  int i;
  PyObject *m,*d, *s, *tmp;
  m = _interface_module = PyModule_Create(&moduledef);
  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _interface (failed to import numpy)"); return m;}
  d = PyModule_GetDict(m);
  s = PyUnicode_FromString("1.21.4");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString(
    "This module '_interface' is auto-generated with f2py (version:1.21.4).\nFunctions:\n"
"  mappingx(nr,nth,nph,yywt_,nx,ny,nz,nnuc,x0,y0,z0,rho_,xnu_,r3c_,r3l_,r3r_,dx,dy,dz,dphi,rhonew_,xnunew_,muc_,mul_,mur_,phic_,phil_,phir_)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString("1.21.4");
  PyDict_SetItemString(d, "__f2py_numpy_version__", s);
  Py_DECREF(s);
  _interface_error = PyErr_NewException ("_interface.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "__interface_error", _interface_error);
  Py_DECREF(_interface_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }

    {
      extern void F_FUNC(mappingx,MAPPINGX)(void);
      PyObject* o = PyDict_GetItemString(d,"mappingx");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(mappingx,MAPPINGX),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("mappingx");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_interface");
#endif
  return m;
}
#ifdef __cplusplus
}
#endif
